name: Build and Publish

on:
  push:
    branches:
      - main

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

jobs:
  security-iac:
    uses: igordevopslabs/custom-workflows-actions/.github/workflows/trivy-iac-scan.yml@main
    with:
      application_name: postgrees-live
    secrets: inherit

  security:
    uses: igordevopslabs/custom-workflows-actions/.github/workflows/trivy-container-scan.yml@main
    with:
      working_directory: "./"
      image_name: postgrees-live
      dockerfile_path: Dockerfile
      tag: main
    secrets: inherit

  push-image-to-docker-hub:
    needs: [security-iac, security]
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Repository
        uses: actions/checkout@v2

      - name: docker login
        id: dockerLogin
        run: | 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Build the Docker image # push The image to the docker hub
        run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}

      - name: Docker Push
        run: docker push $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}