name: Security

on:
  pull_request:
    branches:
      - main

concurrency:
  group: security-checks-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  sonnar-scan:
    uses: igordevopslabs/custom-workflows-actions/.github/workflows/code-quality.yml@main
    with:
      sonnar_project_key: igordevopslabs_postgrees-live
    secrets: inherit

  security-fs:
      uses: igordevopslabs/custom-workflows-actions/.github/workflows/trivy-fs-scan.yml@main
      secrets: inherit

    security-iac:
      uses: igordevopslabs/custom-workflows-actions/.github/workflows/trivy-iac-scan.yml@main
      secrets: inherit

    container-scan:
      uses: igordevopslabs/custom-workflows-actions/.github/workflows/trivy-container-scan.yml@main
      secrets: inherit