name: Security

on:
  pull_request:
    branches:
      - main

concurrency:
  group: security-checks-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  sonnar-scan:
    uses: igordevopslabs/custom-workflows-actions/.github/workflows/code-quality.yml@main
    with:
      sonnar_project_key: igordevopslabs_postgrees-live
    secrets: inherit